//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wordsearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wordsearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dog
        ///cow
        ///cat
        ///horse
        ///donkey
        ///tiger
        ///lion
        ///panther
        ///leopard
        ///cheetah
        ///bear
        ///elephant
        ///polarbear
        ///turtle
        ///tortoise
        ///crocodile
        ///rabbit
        ///porcupine
        ///hare
        ///hen
        ///pigeon
        ///albatross
        ///crow
        ///fish
        ///dolphin
        ///frog
        ///whale
        ///alligator
        ///eagle
        ///squirrel
        ///ostrich
        ///fox
        ///goat
        ///jackal
        ///emu
        ///armadillo
        ///eel
        ///goose
        ///wolf
        ///beagle
        ///gorilla
        ///chimpanzee
        ///monkey
        ///beaver
        ///orangutan
        ///antelope
        ///bat
        ///badger
        ///giraffe
        ///crab
        ///panda
        ///hamster
        ///cobra
        ///shark
        ///camel
        ///hawk
        ///deer
        ///chameleon
        ///hippopotamus
        ///jaguar
        ///chihuahua
        ///cobra
        ///ibex
        ///lizard
        ///koala [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animals {
            get {
                return ResourceManager.GetString("animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua
        ///Blue
        ///BlueViolet
        ///Chartreuse
        ///Chocolate
        ///Coral
        ///Crimson
        ///Cyan
        ///DarkBlue
        ///DarkGreen
        ///DarkOrchid
        ///DeepPink
        ///DarkRed
        ///DarkSeaGreen
        ///Gold
        ///Green
        ///GreenYellow
        ///HotPink
        ///Indigo
        ///LawnGreen
        ///LightGreen
        ///LightPink
        ///LightSalmon
        ///Lime
        ///Magenta
        ///MediumSlateBlue
        ///MediumSpringGreen
        ///MidnightBlue
        ///Navy
        ///Olive
        ///Orange
        ///OrangeRed
        ///Orchid
        ///PaleGreen
        ///PaleVioletRed
        ///Peru
        ///Pink
        ///Purple
        ///Red
        ///RoyalBlue
        ///SeaGreen
        ///Sienna
        ///SkyBlue
        ///SlateBlue
        ///Tan
        ///Teal
        ///Tomato
        ///Turquoise
        ///Violet
        ///Yellow
        ///YellowGreen.
        /// </summary>
        internal static string colours {
            get {
                return ResourceManager.GetString("colours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afghanistan
        ///albania
        ///algeria
        ///andorra
        ///angola
        ///argentina
        ///armenia
        ///australia
        ///austria
        ///azerbaijan
        ///bahamas
        ///bahrain
        ///bangladesh
        ///barbados
        ///belarus
        ///belgium
        ///belize
        ///benin
        ///bhutan
        ///bolivia
        ///botswana
        ///brazil
        ///brunei
        ///bulgaria
        ///burkina
        ///burundi
        ///cambodia
        ///cameroon
        ///canada
        ///chad
        ///chile
        ///china
        ///colombia
        ///comoros
        ///congo
        ///croatia
        ///cuba
        ///cyprus
        ///denmark
        ///djibouti
        ///dominica
        ///ecuador
        ///egypt
        ///eritrea
        ///estonia
        ///ethiopia
        ///fiji
        ///finland
        ///france
        ///gabon
        ///gambia
        ///georgia
        ///germany
        ///ghana
        ///greece
        ///grenada
        ///guatemala
        ///guinea        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cheese
        ///rice
        ///crackers
        ///chicken
        ///beef
        ///potato
        ///tomato
        ///prawn
        ///grape
        ///pepper
        ///pasta
        ///beans
        ///cress
        ///chips
        ///curry
        ///chocolate
        ///duck
        ///fajita
        ///taco
        ///quesadilla
        ///pizza
        ///nugget
        ///onion
        ///caramel
        ///sherbet
        ///grease
        ///mushroom
        ///lasagna
        ///sausage
        ///milk
        ///bread
        ///cake
        ///trifle
        ///ham
        ///beef
        ///spam
        ///risotto.
        /// </summary>
        internal static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apple
        ///avocado
        ///pear
        ///grape
        ///strawberry
        ///raspberry
        ///blueberry
        ///blackcurrant
        ///cherry
        ///plum
        ///apricot
        ///mango
        ///durian
        ///cranberry
        ///pomegranate
        ///melon
        ///grapefruit
        ///pomelo
        ///peach
        ///date
        ///coconut
        ///lychee
        ///banana
        ///persimmon
        ///passionfruit
        ///guava
        ///lemon
        ///lime
        ///dragonfruit
        ///pineapple
        ///fig
        ///.
        /// </summary>
        internal static string fruits {
            get {
                return ResourceManager.GetString("fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------&gt; WELCOME TO MY OBJECTIVELY BAD WORDSEARCH &lt;-----------
        ///If you have come here, I can safely assume that you have been able to choose how many numbers you&apos;d like in your wordsearch. To use the wordsearch, you click on a letter and drag to the end of a word before releasing. If you letters you dragged make an actual word, the letters of that word will change colour and become unselected in the case of multiple words sharing a letter like in an actual wordsearch lmao. To generate a new wordsearch,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpsheet {
            get {
                return ResourceManager.GetString("helpsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aids
        ///aldi
        ///alice
        ///arctic
        ///asda
        ///beige
        ///bellend
        ///boring
        ///brisk
        ///caress
        ///catalyst
        ///celery
        ///chess
        ///chiffon
        ///christen
        ///cringe
        ///data
        ///dreary
        ///dynamite
        ///edible
        ///elbow
        ///election
        ///erect
        ///farts
        ///forensic
        ///frank
        ///golden
        ///granite
        ///grease
        ///haters
        ///heart
        ///hickey
        ///horace
        ///indigo
        ///inert
        ///island
        ///ivory
        ///janet
        ///jaundice
        ///jeans
        ///jester
        ///kelp
        ///khaki
        ///kingdom
        ///kosovo
        ///kraken
        ///leap
        ///leeds
        ///lesbian
        ///lore
        ///lovely
        ///matalan
        ///minority
        ///moobs
        ///nasal
        ///nelson
        ///night
        ///ogres
        ///olive
        ///orange
        ///ozone
        ///papaya
        ///philip
        ///potato
        ///power
        ///privileg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regular {
            get {
                return ResourceManager.GetString("regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celery
        ///carrot
        ///pea
        ///onion
        ///mushroom
        ///broccoli
        ///cauliflower
        ///spinach
        ///leek
        ///corn
        ///lettuce
        ///cucumber
        ///pepper
        ///cabbage
        ///beetroot
        ///cress
        ///kale
        ///turnip
        ///artichoke
        ///squash
        ///okra
        ///garlic
        ///scallion
        ///ginger
        ///parsnip
        ///potato.
        /// </summary>
        internal static string vegetables {
            get {
                return ResourceManager.GetString("vegetables", resourceCulture);
            }
        }
    }
}
