//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wordsearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wordsearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua
        ///Blue
        ///BlueViolet
        ///Chartreuse
        ///Chocolate
        ///Coral
        ///Crimson
        ///Cyan
        ///DarkBlue
        ///DarkGreen
        ///DarkOrchid
        ///DeepPink
        ///DarkRed
        ///DarkSeaGreen
        ///Gold
        ///Green
        ///GreenYellow
        ///HotPink
        ///Indigo
        ///LawnGreen
        ///LightGreen
        ///LightPink
        ///LightSalmon
        ///Lime
        ///Magenta
        ///MediumSlateBlue
        ///MediumSpringGreen
        ///MidnightBlue
        ///Navy
        ///Olive
        ///Orange
        ///OrangeRed
        ///Orchid
        ///PaleGreen
        ///PaleVioletRed
        ///Peru
        ///Pink
        ///Purple
        ///Red
        ///RoyalBlue
        ///SeaGreen
        ///Sienna
        ///SkyBlue
        ///SlateBlue
        ///Tan
        ///Teal
        ///Tomato
        ///Turquoise
        ///Violet
        ///Yellow
        ///YellowGreen.
        /// </summary>
        internal static string colours {
            get {
                return ResourceManager.GetString("colours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------&gt; WELCOME TO MY OBJECTIVELY BAD WORDSEARCH &lt;-----------
        ///If you have come here, I can safely assume that you have been able to choose how many numbers you&apos;d like in your wordsearch. To use the wordsearch, you click on a letter and drag to the end of a word before releasing. If you letters you dragged make an actual word, the letters of that word will change colour and become unselected in the case of multiple words sharing a letter like in an actual wordsearch lmao. To generate a new wordsearch,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpsheet {
            get {
                return ResourceManager.GetString("helpsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aids
        ///aldi
        ///asda
        ///beige
        ///bellend
        ///boring
        ///catalyst
        ///celery
        ///chess
        ///chiffon
        ///christen
        ///cringe
        ///data
        ///dynamite
        ///edible
        ///election
        ///erect
        ///forensic
        ///golden
        ///grease
        ///haters
        ///horace
        ///ivory
        ///janet
        ///jester
        ///kelp
        ///khaki
        ///kingdom
        ///kosovo
        ///leeds
        ///lesbian
        ///matalan
        ///minority
        ///moobs
        ///nasal
        ///nelson
        ///olive
        ///ozone
        ///papaya
        ///philip
        ///potato
        ///power
        ///privilege
        ///purgatory
        ///queencard
        ///quirky
        ///recipe
        ///respect
        ///retainer
        ///salmon
        ///schofield
        ///shrek
        ///sixteen
        ///spring
        ///stairs
        ///stapler
        ///stress
        ///tomato
        ///trashy
        ///treasure
        ///trolley
        ///unicycle
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
